In [ ]:
import tensorflow as tf
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv('./leap_data.csv')

In [ ]:
df.describe()

hands      fingers       R_hand  R_palmpos_x  R_palmpos_y  \
count  9417.000000  9417.000000  9417.000000  9417.000000  9417.000000   
mean      1.006902     5.034512     0.465329    17.149131    -9.577918   
std       0.628256     3.141281     0.498823    32.657931    43.573616   
min       0.000000     0.000000     0.000000  -126.004930  -179.945680   
25%       1.000000     5.000000     0.000000     0.000000   -15.550946   
50%       1.000000     5.000000     0.000000     0.000000     0.000000   
75%       1.000000     5.000000     1.000000    34.434174     0.000000   
max       2.000000    10.000000     1.000000   159.988645   178.988470   

       R_palmpos_z  R_palmvel_x  R_palmvel_y  R_palmvel_z      R_pitch  ...  \
count  9417.000000  9417.000000  9417.000000  9417.000000  9417.000000  ...   
mean     -8.255903    19.253144   108.175465     6.775617    11.636102  ...   
std      34.531135    77.849343   127.429367    46.576734   326.572676  ...   
min    -179.782302  -276.384857     0.000000  -169.011322 -2677.569824  ...   
25%     -15.294696     0.000000     0.000000     0.000000     0.000000  ...   
50%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
75%       0.000000    55.089859   215.238602     5.186865     0.000000  ...   
max     179.697730   347.699310   481.505737   260.980133  2749.246094  ...   

           L_pitch        L_roll        L_yaw  L_arm_dir_x  L_arm_dir_y  \
count  9417.000000  9.417000e+03  9417.000000  9417.000000  9417.000000   
mean      4.508340 -2.462508e+00     6.811722     0.183754     0.171617   
std     344.356405  2.040093e+02   260.146907     0.292609     0.241608   
min   -2214.096191 -1.525736e+03 -2195.272949    -0.886738    -0.775825   
25%      -7.129094 -1.865118e+01    -8.049717     0.000000     0.000000   
50%       0.000000  0.000000e+00     0.000000     0.000000     0.000000   
75%      14.032420  1.192093e-07     6.450735     0.377067     0.355272   
max    2504.065186  1.561921e+03  1751.699463     0.998943     0.999995   

       L_arm_dir_z  L_wristpos_x  L_wristpos_y  L_wristpos_z      gesture  
count  9417.000000   9417.000000   9417.000000   9417.000000  9417.000000  
mean     -0.411003    -42.667712    112.115926     24.979206     2.453011  
std       0.405605     78.783490    117.287866     53.383201     1.680308  
min      -0.999823   -313.034485      0.000000   -107.027306     0.000000  
25%      -0.816869   -118.175522      0.000000      0.000000     1.000000  
50%      -0.477637      0.000000    117.164688      0.000000     3.000000  
75%       0.000000      0.000000    198.627579     49.871426     4.000000  
max       0.837319    374.252838    471.342194    265.634918     5.000000  

[8 rows x 35 columns]

In [ ]:
shape = df.shape
shape

(9417, 35)

In [ ]:
Y = df['gesture']
X = df.drop('gesture',axis=1)

In [ ]:
x = np.array(X)
y = np.array(Y)

In [ ]:
print(x.shape, y.shape)

(9417, 34) (9417,)


In [ ]:
y.shape[0]

9417

In [ ]:
y = np.reshape(y, (y.shape[0], 1))

In [ ]:
print(x.shape, y.shape)

(9417, 34) (9417, 1)


In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [ ]:
scal = scaler.fit(x)
x = scal.transform(x)

In [ ]:
x

array([[-1.60277883, -1.60277883, -0.93290291, ...,  0.54161066,
        -0.95595464, -0.46794745],
       [-1.60277883, -1.60277883, -0.93290291, ...,  0.54161066,
        -0.95595464, -0.46794745],
       [-1.60277883, -1.60277883, -0.93290291, ...,  0.54161066,
        -0.95595464, -0.46794745],
       ...,
       [-1.60277883, -1.60277883, -0.93290291, ...,  0.54161066,
        -0.95595464, -0.46794745],
       [-1.60277883, -1.60277883, -0.93290291, ...,  0.54161066,
        -0.95595464, -0.46794745],
       [-1.60277883, -1.60277883, -0.93290291, ...,  0.54161066,
        -0.95595464, -0.46794745]])

In [ ]:
from pprint import pprint

In [ ]:
pprint(x)

array([[-1.60277883, -1.60277883, -0.93290291, ...,  0.54161066,
        -0.95595464, -0.46794745],
       [-1.60277883, -1.60277883, -0.93290291, ...,  0.54161066,
        -0.95595464, -0.46794745],
       [-1.60277883, -1.60277883, -0.93290291, ...,  0.54161066,
        -0.95595464, -0.46794745],
       ...,
       [-1.60277883, -1.60277883, -0.93290291, ...,  0.54161066,
        -0.95595464, -0.46794745],
       [-1.60277883, -1.60277883, -0.93290291, ...,  0.54161066,
        -0.95595464, -0.46794745],
       [-1.60277883, -1.60277883, -0.93290291, ...,  0.54161066,
        -0.95595464, -0.46794745]])


In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.33, random_state = 42)

In [ ]:
print(x_train.shape,y_train.shape,x_test.shape,y_test.shape)

(6309, 34) (6309, 1) (3108, 34) (3108, 1)


In [ ]:
Model = tf.keras.Sequential([
    tf.keras.layers.Dense(units = 120, activation='relu'),
    tf.keras.layers.Dense(units = 120, activation='relu'),
    tf.keras.layers.Dense(units = 80, activation='relu'),
    # tf.keras.layers.Dense(units = 10, activation='relu'),
    tf.keras.layers.Dense(units = 6, activation='softmax')
])

In [ ]:
Model.compile(optimizer='adam',loss='SparseCategoricalCrossentropy',metrics=['accuracy'])

In [ ]:
Model.fit(x_train,y_train,epochs = 20,validation_data=(x_test,y_test),verbose=2)

Epoch 1/20
198/198 - 3s - loss: 0.9716 - accuracy: 0.6339 - val_loss: 0.5926 - val_accuracy: 0.7873 - 3s/epoch - 14ms/step
Epoch 2/20
198/198 - 1s - loss: 0.5135 - accuracy: 0.8004 - val_loss: 0.4682 - val_accuracy: 0.8205 - 867ms/epoch - 4ms/step
Epoch 3/20
198/198 - 1s - loss: 0.4247 - accuracy: 0.8325 - val_loss: 0.4080 - val_accuracy: 0.8388 - 1s/epoch - 7ms/step
Epoch 4/20
198/198 - 1s - loss: 0.3922 - accuracy: 0.8379 - val_loss: 0.3851 - val_accuracy: 0.8488 - 990ms/epoch - 5ms/step
Epoch 5/20
198/198 - 1s - loss: 0.3715 - accuracy: 0.8483 - val_loss: 0.3754 - val_accuracy: 0.8507 - 985ms/epoch - 5ms/step
Epoch 6/20
198/198 - 1s - loss: 0.3582 - accuracy: 0.8486 - val_loss: 0.3758 - val_accuracy: 0.8333 - 946ms/epoch - 5ms/step
Epoch 7/20
198/198 - 1s - loss: 0.3489 - accuracy: 0.8545 - val_loss: 0.3682 - val_accuracy: 0.8526 - 966ms/epoch - 5ms/step
Epoch 8/20
198/198 - 1s - loss: 0.3410 - accuracy: 0.8540 - val_loss: 0.3590 - val_accuracy: 0.8539 - 920ms/epoch - 5ms/step
Epoch

In [ ]:
Model.evaluate(x_test, y_test)

98/98 [==============================] - 0s 3ms/step - loss: 0.3638 - accuracy: 0.8514


[0.3637523949146271, 0.8513513803482056]

In [ ]:
results = Model.predict(x_test)

98/98 [==============================] - 1s 2ms/step


In [ ]:
results.shape

(3108, 6)

In [ ]:
results[1]

array([9.9975538e-01, 2.3709217e-04, 5.2584681e-10, 3.1321542e-06,
       1.3377896e-08, 4.5251404e-06], dtype=float32)

In [ ]:
np.argmax(results[1])

0

In [ ]:
Model.save('model.h5')

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3079: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(
